// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tigdqzfwrqzpavtylhaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpZ2RxemZ3cnF6cGF2dHlsaGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjA1OTIsImV4cCI6MjA3NDAzNjU5Mn0.U96SkIANifmGTq1lNi1QiOnqW0KFLgezpDXOclnG_1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});